### ISSUE TITLE
Add Solidity support

### ISSUE THREAD

**Issue by michael-cohen-io** [ahmadnassri/httpsnippet#236]
Some of the biggest Web3 projects out there use Readme.io, which relies on this project for language support. Adding solidity support would go a very long way for this new subindustry

**Comment by erunion** [comment]
Hey @michael-cohen-eth I head up our integration of this project over with ReadMe. I don't have any experience with Solidity but from what I gather it doesn't seem to be an HTTP client. Are you looking ReadMe, and this project, to add support for it or are you instead looking for code highlighting support for Solidity on ReadMe?

**Comment by michael-cohen-io** [comment]
Hey @erunion, I'm looking for the latter, I believe. I had reached out to Readme about this subject and got the following response which might shed more context:

```
Hi Michael,
Thanks for reaching out; my name is Darren from ReadMe Support and I'll be assisting you today!

﻿There haven't been any talks as far as I know, but I know we do build off of HTTPSnippet so if they support Solidity, it will be a lot easier for us to support it.
Let me know if you have any questions, Michael!
Best,
﻿Darren
```

Really my endgoal is to support adding snippets to my team's documentation in Solidity as well as Recipes on the website in Solidity

**Comment by erunion** [comment]
@michael-cohen-eth Sounds good, we can do that! I'm moving this over to https://github.com/readmeio/syntax-highlighter/pull/219 if you want to close this out.

**Comment by michael-cohen-io** [comment]
Thank you very much for your support here. Looking forward to seeing this in the future :D
