### ISSUE TITLE
Wiki is empty

### ISSUE THREAD

**Issue by sh-cho** [ahmadnassri/httpsnippet#313]
I'm trying to make dart conversion, but wiki is empty.

https://github.com/Kong/httpsnippet/wiki/_history

Well looks like someone removed all guides. (Why?)

https://github.com/Kong/httpsnippet/wiki/_compare/8a506dc51f2b74e804875b9a7a42dbd9e20306b6...99a0fb1f6c9d3080e7d67e040a91fc750731591b

I can check contribution guide through revision but maybe you guys should restrict editing wiki to contributors only.

**Comment by filfreire** [comment]
reverted and added protection to the wiki, thanks @sh-cho
