### ISSUE TITLE
Update README.md and Wiki

### ISSUE THREAD

**Issue by SKPG-Tech** [ahmadnassri/httpsnippet#327]
As I went through the README, I was pleased to find that Rust was included in the Quick Start guide and the CLI usage example. However, I later discovered that Rust is not yet an implemented target. In that case, it would be better if the README didn't mention Rust until the target is implemented, possibly with the use of `reqwest`, `hyper`, `actix-web`, or any other related crate.

Moreover, I believe that the Wiki can be improved to make it more user-friendly. The current layout can be confusing, and the TypeScript library usage (especially the types) can be moved to the Wiki and linked to in the README. This would make it more informative and keep everything in one place, rather than scattered throughout different sources.

Perhaps there are other areas that could be improved, and I would appreciate any thoughts on how to rework this. If this is something that is desirable, I am more than happy to assist. It would be my first time doing something like this, and I am willing to try my best 😄

**Comment by Benjscho** [comment]
Just added a PR for enabling Rust support with `reqwest` waiting on review: https://github.com/Kong/httpsnippet/pull/328
