### ISSUE TITLE
Maintainer activity

### ISSUE THREAD

**Issue by Benjscho** [ahmadnassri/httpsnippet#331]
Hi There, what is the current status of maintenance of this project? There are a few open pull requests that would add features/new targets, but haven't been looked at by the maintainers. E.g., I created PR#328 that would add Rust as a target because I loved using Insomnia and wanted to add the code generation to the project. Is there any way community can help support or is maintaining the snippet library just on the backburner for Kong? Totally valid if it is!

**Comment by subnetmarco** [comment]
Hi @Benjscho - We need to add an official maintainer to the project, I will try to make it happen in the next 6 months but also looking for volunteers.

**Comment by Benjscho** [comment]
Hi Marco, sounds great, thank you! I'd be happy to volunteer to help review PRs and triage issues in the meantime

**Comment by subnetmarco** [comment]
Thanks for offering! Can we hop on a call first? You can send me an email at: marco at konghq dot com

**Comment by brianvoe** [comment]
Any update on this? Im about to rewrite my own from scratch. 

If you need someone to maintain this i can as well. I manage github.com/brianvoe/slim-select and github.com/brianvoe/gofakeit

**Comment by subnetmarco** [comment]
@brianvoe thanks for the offer. Could you please reach out to me via email? marco at konghq dot com

**Comment by brianvoe** [comment]
email sent.

**Comment by subnetmarco** [comment]
I didn't receive it, but I just sent you one.
