### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by Justman100** [ahmadnassri/httpsnippet#337]
@saisatishkarra

For got to public a new version?

**Comment by saisatishkarra** [comment]
[PR](https://github.com/Kong/httpsnippet/pull/336) is a CICD-related change and has nothing to do with the product. Does it require a new release of httpsnippet? How is the release managed/made? Can the team help achieve this as per the cycle / release process as needed? cc: @vs-kong / @filfreire

**Comment by Justman100** [comment]
> [PR](https://github.com/Kong/httpsnippet/pull/336) is a CICD-related change and has nothing to do with the product. Does it require a new release of httpsnippet? How is the release managed/made? Can the team help achieve this as per the cycle / release process as needed? cc: @vs-kong / @filfreire

Dude! The last release 2.0.0 is from Sep 3, 2021, since then 38 commits have been released!

**Comment by filfreire** [comment]
We'll be doing a release soon.

**Comment by Justman100** [comment]
> We'll be doing a release soon.

When? Is still not out
